vim.g.colors_name = "kalidots"

local set = vim.api.nvim_set_hl
local p = {
  bg = "#0b0a10",
  bg_alt = "#15121c",
  bg_soft = "#1d1826",
  bg_visual = "#2a2035",
  bg_search = "#3b2233",
  fg = "#e8dfe7",
  fg_muted = "#b7a8b8",
  fg_subtle = "#8d7a90",
  border = "#3a2a3f",
  accent = "#ff7aa2",
  accent_2 = "#ffb3c7",
  red = "#ff6f91",
  orange = "#ff9c6a",
  yellow = "#f5d76e",
  green = "#9dd274",
  cyan = "#7fd6d4",
  blue = "#8fb4ff",
  purple = "#c6a0ff",
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.o.background = "dark"

local highlights = {
  Normal = { fg = p.fg, bg = p.bg },
  NormalFloat = { fg = p.fg, bg = p.bg_alt },
  FloatBorder = { fg = p.border, bg = p.bg_alt },
  FloatTitle = { fg = p.accent, bg = p.bg_alt, bold = true },
  ColorColumn = { bg = p.bg_alt },
  Conceal = { fg = p.fg_subtle },
  Cursor = { fg = p.bg, bg = p.accent },
  CursorColumn = { bg = p.bg_alt },
  CursorLine = { bg = p.bg_alt },
  CursorLineNr = { fg = p.accent_2, bold = true },
  Directory = { fg = p.blue },
  EndOfBuffer = { fg = p.bg },
  ErrorMsg = { fg = p.red },
  FoldColumn = { fg = p.fg_subtle, bg = p.bg },
  Folded = { fg = p.fg_muted, bg = p.bg_alt },
  IncSearch = { fg = p.bg, bg = p.accent_2, bold = true },
  LineNr = { fg = p.fg_subtle },
  MatchParen = { fg = p.accent_2, bg = p.bg_visual, bold = true },
  ModeMsg = { fg = p.green, bold = true },
  MoreMsg = { fg = p.green },
  NonText = { fg = p.border },
  Pmenu = { fg = p.fg, bg = p.bg_alt },
  PmenuSel = { fg = p.fg, bg = p.bg_visual, bold = true },
  PmenuSbar = { bg = p.bg_soft },
  PmenuThumb = { bg = p.border },
  Question = { fg = p.blue },
  Search = { fg = p.fg, bg = p.bg_search },
  SignColumn = { fg = p.fg_subtle, bg = p.bg },
  SpecialKey = { fg = p.fg_subtle },
  SpellBad = { sp = p.red, undercurl = true },
  SpellCap = { sp = p.blue, undercurl = true },
  SpellLocal = { sp = p.cyan, undercurl = true },
  SpellRare = { sp = p.purple, undercurl = true },
  StatusLine = { fg = p.fg, bg = p.bg_soft },
  StatusLineNC = { fg = p.fg_subtle, bg = p.bg_alt },
  TabLine = { fg = p.fg_muted, bg = p.bg_alt },
  TabLineFill = { bg = p.bg_alt },
  TabLineSel = { fg = p.fg, bg = p.bg_visual, bold = true },
  Title = { fg = p.accent_2, bold = true },
  VertSplit = { fg = p.border, bg = p.bg },
  Visual = { bg = p.bg_visual },
  WarningMsg = { fg = p.orange },
  Whitespace = { fg = p.border },
  WinSeparator = { fg = p.border, bg = p.bg },

  Comment = { fg = p.fg_subtle, italic = true },
  Constant = { fg = p.orange },
  String = { fg = p.green },
  Character = { fg = p.green },
  Number = { fg = p.orange },
  Boolean = { fg = p.orange, bold = true },
  Float = { fg = p.orange },
  Identifier = { fg = p.fg },
  Function = { fg = p.blue },
  Statement = { fg = p.accent },
  Conditional = { fg = p.purple },
  Repeat = { fg = p.purple },
  Label = { fg = p.accent_2 },
  Operator = { fg = p.fg_muted },
  Keyword = { fg = p.accent },
  Exception = { fg = p.red },
  PreProc = { fg = p.yellow },
  Include = { fg = p.purple },
  Define = { fg = p.purple },
  Macro = { fg = p.yellow },
  PreCondit = { fg = p.yellow },
  Type = { fg = p.cyan },
  StorageClass = { fg = p.cyan },
  Structure = { fg = p.cyan },
  Typedef = { fg = p.cyan },
  Special = { fg = p.accent_2 },
  SpecialChar = { fg = p.accent_2 },
  Tag = { fg = p.blue },
  Delimiter = { fg = p.fg_muted },
  SpecialComment = { fg = p.fg_subtle },
  Debug = { fg = p.red },
  Underlined = { fg = p.blue, underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = p.red },
  Todo = { fg = p.bg, bg = p.yellow, bold = true },

  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.orange },
  DiagnosticInfo = { fg = p.blue },
  DiagnosticHint = { fg = p.cyan },
  DiagnosticOk = { fg = p.green },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },

  DiffAdd = { fg = p.green, bg = "#132018" },
  DiffChange = { fg = p.blue, bg = "#141d2a" },
  DiffDelete = { fg = p.red, bg = "#2a161d" },
  DiffText = { fg = p.accent_2, bg = "#2c2436" },

  GitSignsAdd = { fg = p.green },
  GitSignsChange = { fg = p.blue },
  GitSignsDelete = { fg = p.red },
}

for group, spec in pairs(highlights) do
  set(0, group, spec)
end

local links = {
  CurSearch = "IncSearch",
  QuickFixLine = "Visual",
  WinBar = "StatusLine",
  WinBarNC = "StatusLineNC",
  NormalNC = "Normal",
 ["@variable"] = "Identifier",
 ["@variable.builtin"] = "Special",
 ["@constant"] = "Constant",
 ["@string"] = "String",
 ["@number"] = "Number",
 ["@boolean"] = "Boolean",
 ["@function"] = "Function",
 ["@function.builtin"] = "Special",
 ["@keyword"] = "Keyword",
 ["@keyword.return"] = "Keyword",
 ["@type"] = "Type",
 ["@type.builtin"] = "Type",
 ["@comment"] = "Comment",
 ["@punctuation.delimiter"] = "Delimiter",
 ["@punctuation.bracket"] = "Delimiter",
 ["@tag"] = "Tag",
 ["@tag.attribute"] = "Identifier",
 ["@property"] = "Identifier",
 ["@constructor"] = "Type",
 ["@module"] = "Identifier",
}

for group, target in pairs(links) do
  set(0, group, { link = target })
end
